<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Import Project="..\..\Directory.Build.props" />
  <Import Project="..\OrchardCore.Build\OrchardCore.Commons.props" />
  <Import Project="..\OrchardCore\OrchardCore.Module.Targets\OrchardCore.Module.Targets.props" />

  <PropertyGroup>
    <OrchardCorePath>$(MSBuildThisFileDirectory)..\..\</OrchardCorePath>
    <ZeptoOrchardCoreModulesPath>$(MSBuildThisFileDirectory)</ZeptoOrchardCoreModulesPath>
    <TargetFrameworks>$(CommonTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

</Project>